### ISSUE TITLE
Arcanum diamonds are registering as normal diamonds which blocks crafting.

### ISSUE THREAD

**Issue by ProsperCraft** [HellBreecher/Arcanum#1]
My users are reporting that as of the last update arcanum diamonds are being ore dictionared as normal diamonds which is blocking the crafting of infernal diamond armor.

Modpack- 

Ancient TownCraft-
https://minecraft.curseforge.com/projects/ancient-towncraft

**Comment by HellBreecher** [comment]
Fixed in version 4.2.7.0 which has been submitted for approval. Should be out within 12 hours easily
