### ISSUE TITLE
Finding Blood Diamonds/Void Diamonds

### ISSUE THREAD

**Issue by ghost** [HellBreecher/Arcanum#3]
There needs to be some config option to set the spawn rate of the ores in this mod. I want to make the diamonds more common, but currently this is impossible without external mods. As it is, they are too rare.

**Comment by HellBreecher** [comment]
The rarity is intentional due to how overpowered the armor tiers can get. Its made to help balance out the mod. While configs will be in the 1.16.2 version im working on as well I wont be implementing config options for spawn rates.
