### ISSUE TITLE
armor interferes with HP increases

### ISSUE THREAD

**Issue by Iashar** [HellBreecher/Arcanum#5]
**Describe the bug**
The infernal armor interferes with health boosting.
so, I have various ways in my modpack to increase my players health, but as soon as I place a peice of the infernal armor -in my inventory, hotbar or armor slot-, it sets my hp at a single row of hearts, even though I have 2 sets of them.
Thankfully, no crashes, just strange behavior.

**To Reproduce**
1. get more hearts than normally possible, usually by a mod
2. Craft or find infernal armor 
3. watch overcharged health get removed

**Expected behavior**
I figured that armor wouldn't interfere with health....?

**Screenshots**
https://www.dropbox.com/s/eq4mab3nzou3djd/Screenshot%202021-03-18%2019.38.59.png?dl=0
placed boots in chest to regen some of my second set of hearts
https://www.dropbox.com/s/eeerl8awxdabh88/Screenshot%202021-03-18%2019.39.24.png?dl=0
can see there is multiple sets overlayed on eachother
https://www.dropbox.com/s/lgggvvna2x4qzyt/Screenshot%202021-03-18%2019.39.37.png?dl=0
dropped boots from chest inventory
https://www.dropbox.com/s/48mgh587nrmhzru/Screenshot%202021-03-18%2019.39.46.png?dl=0
as soon as I pick them up, my second row of hearts is ripped off, but continues trying to regen, causing increased food drain.

**My Setup:**
 - Minecraft: [1.16.5]
 - Forge: [1.16.5-forge-36.0.55]
 - Arcanum: [arcanum_1.16.4-6.0.0.0-beta4]
 - Modpack: [custom]
 - baubley-heart-canisters-1.16.4-1.1.2
 - overloadedarmorbar-5.1.0
 - ScalingHealth-1.16.4-4.0.4+4
 - various other mods(over 200), though I think with just one or 2 of these the bug should be reproducible.

**Comment by HellBreecher** [comment]
This is actually a weird one. I'll look into it. Technically it does interfere with health but only when the full armor set is applied to the armor slot, as it fills the maximum default health (20). Though just having the item in your inventory shouldn't cause this issue.

**Comment by HellBreecher** [comment]
Resolved in Arcanum 1.16.5 - 6.1.0.0
